version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: TesteVr
      POSTGRES_USER: postgres
      POSTGRES_DB: TesteVr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: